In [1]:
!pip install tensorflow

     |████████████████████████████████| 585.9 MB 6.1 kB/s  eta 0:00:01    |██▎                             | 42.2 MB 22.6 MB/s eta 0:00:25     |██████████▎                     | 189.0 MB 81.7 MB/s eta 0:00:05   | 357.9 MB 496 kB/s eta 0:07:40MB/s eta 0:00:02
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 17.1 MB 480 kB/s eta 0:00:01
     |████████████████████████████████| 2.4 MB 479 kB/s eta 0:00:01
     |████████████████████████████████| 5.1 MB 487 kB/s eta 0:00:01
  Using cached libclang-16.0.0-py2.py3-none-manylinux2010_x86_64.whl (22.9 MB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 81 kB 15.6 M

In [3]:
import tensorflow as tf
import numpy as np

2023-06-06 20:11:05.628388: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-06 20:11:05.700902: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-06 20:11:05.701500: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-06 20:11:06.917452: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [4]:
# Tensor with 0-Dimension
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
# Tensor with 1-Diemension

tensor_one_d = tf.constant([2,0.,-3,8,90],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [6]:
# Tensor with 2-Dimension
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [7]:
# Tensor with 3-Dimension
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

])
print(tensor_three_d)
print(tensor_three_d.ndim)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
3
