<a href="https://colab.research.google.com/github/Praveenku32k/Sentiment_Analysis/blob/main/TensorFlow_Tensor_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Importing the tensorflow laberary
import tensorflow as tf

In [2]:
# Importing Numpy labrary
import numpy as np


In [4]:
#Taking one example
tensor_indexed=tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)


In [7]:
print(tensor_indexed[:4]) # first four value we  will get.

tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)


In [10]:
print(tensor_indexed[1:5+1])

tf.Tensor([ 6  2  4  6 66], shape=(5,), dtype=int32)


In [11]:
tf.range(1,5+1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [12]:
tensor_two_d=tf.constant([[1,2,0],
                         [3,5,-1],
                          [1,5,6],
                          [2,3,8]])

In [13]:
print(tensor_two_d[ 0:3,0:2 ])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [14]:
print(tensor_two_d[0:3, :])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [16]:
print(tensor_two_d[:,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [17]:
print(tensor_two_d[:,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [20]:
tensor_three_d= tf.constant([

                             [[1,2.0],
                             [3,5,-1]],

                             [[10,2,0],
                              [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]

                             ])

ValueError: ignored